### PR TITLE
feat: common static assets in @apify/docs-theme

### PR DESCRIPTION
**Pull request by barjin**

### CODE REVIEW

**Review by B4nan — APPROVED** [review]
nice!

**Review by B4nan — CHANGES_REQUESTED** [review]
hmm but the images for the docs content should stay as they were, or not?

**Comment by barjin** [comment]
Did some grep-based pruning on the "shared" assets (and a quick manual check) - the theme `/static` folder should only contain files required directly by the theme now.

**Comment by barjin** [comment]
Did some grep-based pruning on the "shared" assets (and a quick manual check) - the theme `/static` folder should only contain files required directly by the theme now.

**Review by B4nan — APPROVED** [review]
feel free to merge, as well as the other related one

**Pull request merged**
